engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  radon:
    enabled: true
  tslint:
    enabled: true
    channel: beta
    config: .tslint.json
  markdownlint:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.ts"
    - "**.py"
    - "**.md"
exclude_paths:
  - tests/
  - server/static
  - core/protobuf
