---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        python:
          mass_threshold: 100
#  pep8:
#    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  tslint:
    enabled: true
    channel: beta
    config: .tslint.json
ratings:
  paths:
  - "**.css"
  - "**.ts"
  - "**.py"
exclude_paths:
- tests/
- server/static
